---
title: "R Notebook"
output: html_notebook
---

```{r}
suppressPackageStartupMessages({
library(tidyverse)
library(patchwork)
theme_set(theme_bw())
library(tidymodels)
library(arrow)
})
```

# Import Data:

```{r}
Tor_hitting <- read_csv("TOR_batting.csv")
```

# Cleaning:

```{r}
Tor_hitting_clean <- Tor_hitting |>
  select(-Rank) |>
  mutate(
    day = 1,
    month = 1,
    year = make_date(Year, month, day)
    ) |>
  select(-Year, -day, -month) |>
  select(year, everything()) |>
  group_by(year) |>
  rename(c(
    "G" = Games,
    "PA" = Plate_Appearances,
    "AB" = At_Bats,
    "R" = Runs,
    "H" = Hits,
    "2B" = Doubles,
    "3B" = Triples,
    "HR" = Home_Runs,
    "RBI" = Runs_Batted_In,
    "SB" = Stolen_Bases,
    "CS" = Caught_Stealing,
    "BB" = Base_On_Balls,
    "K" = Strikeouts,
    "AVG" = Batting_Average,
    "OBP" = On_Base_Percentage,
    "SLG" = Slugging_Percentage,
    "OPS" = On_Base_Plus_Slugging_Percentage,
    "OPS+" = On_Base_Plus_Slugging_Percentage_Plus,
    "TB" = Total_Bases,
    "GIDP" = Double_Plays_Grounded_Into,
    "HBP" = Times_Hit_By_Pitch,
    "SAC" = Sacrifice_Hits,
    "SF" = Sacrifice_Flies,
    "IBB" = Intentional_Bases_on_Balls
  )) |>
  summarise(
    OBP_average = (sum(H) + sum(BB) + sum(HBP))/(sum(AB)+sum(BB) + sum(HBP) + sum(SF)),
    SLG_average = sum(TB)/sum(AB),
    OPS_average = OBP_average + SLG_average
  )

Tor_hitting_clean
```

# Split into training, validation and testing data:

```{r}
hitting_split <- 
  initial_validation_split(Tor_hitting, prop = c(0.6, 0.2))
  training <- training(hitting_split)
  validation <- validation(hitting_split)
  test <- testing(hitting_split)
hitting_split
```
